### ISSUE TITLE
Series Filter Issue

### ISSUE THREAD

**Issue by A1Marky** [kellenwiltshire/fliptheshow#9]
I checked out the site and noticed that the Filter for Series wasn't updating the data when I switched it to filter "Live" series only.

**Comment by kellenwiltshire** [comment]
Thanks for noticing that! I will work on fixing the issue right away.

**Comment by kellenwiltshire** [comment]
Issue Fixed! Thanks for your help @A1Marky !

**Comment by A1Marky** [comment]
> Issue Fixed! Thanks for your help @A1Marky !
No problem. Thanks! Another nice touch you could add would be a button linking to the MLB The show market place next to the item that is displayed so you could see the player or item you're interested in and click the button to be directed right to it for purchase.

**Comment by kellenwiltshire** [comment]
@A1Marky That's a good idea. I will see if I can implement that in the next little while! Shouldn't be too difficult if I can find the time!

**Comment by A1Marky** [comment]
> @A1Marky That's a good idea. I will see if I can implement that in the next little while! Shouldn't be too difficult if I can find the time!

Sounds good. If the data is being pulled from The Show API how often is this data being pulled/refreshed? For someone like me on the outside using the website I think the greatest utility would be to be able to refresh the data in the tables without losing the filters that were used. This would be useful for trying to find good profit deals with speed along with that buy button I mentioned before.

**Comment by kellenwiltshire** [comment]
@A1Marky The data is being pulled from the API whenever the page is loaded. However, due to how NextJS grabs data and the sheer AMOUNT of data from the API, at first load of the day it could be out of date. Unfortunately I don't know how to get around this delay. 

What this means is that it loads the LAST grabbed data. That could be from 5 minutes ago, that could be from 5 days ago depending on traffic. It takes the server roughly 3 minutes to grab the large list of card data for the Players, much faster for the stadiums and equipment. When it doubt, reload the page and it should have grabbed the newest data from the API.

I will look at adding a quick link to the Item page on the marketplace, that should be a simple thing to do. However, I don't have the time to add an auto-refresh and store table filters. However, if you wanted to make a PR I would be happy to merge it!

**Comment by kellenwiltshire** [comment]
Fair enough!

Thanks for your input though. Glad to have someone use my creation. Hopefully in the future I will have the time and motivation to keep growing it!

Thanks again!

**Comment by kellenwiltshire** [comment]
@A1Marky Good news! A button has been added to open up the marketplace listing for the items as requested!

I am also getting pretty close on auto-refreshing the data while keeping the same filters as well. Should hopefully have that done in the next few days!

**Comment by kellenwiltshire** [comment]
@A1Marky And auto-refreshing is implemented. It requests updated data every 30 seconds. 

The Players page will show updated data every couple minutes (since it has SO much to grab). Equipment and Stadiums update roughly around the 30 second mark. 

Hope this brings you great profit!
